.TH "src Directory Reference" 3 "Fri Nov 12 2021" "Version 1.0" "DIY Auto-Correlator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBfeatureline1\&.hpp\fP"
.br
.ti -1c
.RI "file \fBfeatureline2\&.hpp\fP"
.br
.ti -1c
.RI "file \fBfeatureline3\&.hpp\fP"
.br
.ti -1c
.RI "file \fBglobal\&.cpp\fP"
.br
.ti -1c
.RI "file \fBglobal\&.hpp\fP"
.br
.ti -1c
.RI "file \fBledpanel\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmain\&.cpp\fP"
.br
.ti -1c
.RI "file \fButilities\&.cpp\fP"
.br
.in -1c
