.TH "/mnt/m/code/Correlator/Software Directory Reference" 3 "Mon Aug 30 2021" "Version 1.0" "DIY Auto-Correlator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/mnt/m/code/Correlator/Software Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBaccumulator\&.hpp\fP"
.br
.ti -1c
.RI "file \fBcircular_buffer\&.hpp\fP"
.br
.ti -1c
.RI "file \fBdiscarder\&.hpp\fP"
.br
.ti -1c
.RI "file \fBLin_ACorr_RT_Base\&.hpp\fP"
.br
.ti -1c
.RI "file \fBLin_ACorr_RT_Teensy\&.hpp\fP"
.br
.ti -1c
.RI "file \fBLin_CrossCorr_RT_Base\&.hpp\fP"
.br
.ti -1c
.RI "file \fBLin_CrossCorr_RT_Teensy\&.hpp\fP"
.br
.ti -1c
.RI "file \fBmulti_tau\&.hpp\fP"
.br
.ti -1c
.RI "file \fBsimpler_circular_buffer\&.hpp\fP"
.br
.ti -1c
.RI "file \fBtest\&.cpp\fP"
.br
.ti -1c
.RI "file \fBtypes\&.hpp\fP"
.br
.in -1c
