.TH "code/software Directory Reference" 3 "Thu Oct 14 2021" "Version 1.0" "DIY Auto-Correlator and Photon Statistics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/software Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBaccumulator\&.hpp\fP"
.br
.ti -1c
.RI "file \fBdiscarder\&.hpp\fP"
.br
.ti -1c
.RI "file \fBhistogram\&.hpp\fP"
.br
.ti -1c
.RI "file \fBLin_ACorr_RT_Teensy\&.hpp\fP"
.br
.ti -1c
.RI "file \fBLin_CrossCorr_RT_Teensy\&.hpp\fP"
.br
.ti -1c
.RI "file \fBmonitor_channel\&.hpp\fP"
.br
.ti -1c
.RI "file \fBmulti_tau\&.hpp\fP"
.br
.ti -1c
.RI "file \fBpseudoSerial\&.cpp\fP"
.br
.ti -1c
.RI "file \fBpseudoSerial\&.hpp\fP"
.br
.ti -1c
.RI "file \fBsimpler_circular_buffer\&.hpp\fP"
.br
.ti -1c
.RI "file \fBtest\&.cpp\fP"
.br
.in -1c
