.TH "code/hardware Directory Reference" 3 "Thu Oct 14 2021" "Version 1.0" "DIY Auto-Correlator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/hardware Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBerrors\&.hpp\fP"
.br
.ti -1c
.RI "file \fBinterarrival\&.hpp\fP"
.br
.ti -1c
.RI "file \fBledpanel\&.hpp\fP"
.br
.ti -1c
.RI "file \fBledset\&.hpp\fP"
.br
.ti -1c
.RI "file \fBlifetime_timer\&.hpp\fP"
.br
.ti -1c
.RI "file \fBperf_counter\&.hpp\fP"
.br
.ti -1c
.RI "file \fBpins\&.hpp\fP"
.br
.ti -1c
.RI "file \fBpit\&.hpp\fP"
.br
.ti -1c
.RI "file \fBqtmr1\&.hpp\fP"
.br
.ti -1c
.RI "file \fButilities\&.hpp\fP"
.br
.in -1c
