.TH "code/pc_app Directory Reference" 3 "Fri Nov 12 2021" "Version 1.0" "DIY Auto-Correlator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/pc_app Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBconfig\&.py\fP"
.br
.ti -1c
.RI "file \fBdevice_mode\&.py\fP"
.br
.ti -1c
.RI "file \fBlive_graph\&.py\fP"
.br
.ti -1c
.RI "file \fBlivegraph\&.py\fP"
.br
.ti -1c
.RI "file \fBmultitau\&.py\fP"
.br
.ti -1c
.RI "file \fBnew_app\&.py\fP"
.br
.ti -1c
.RI "file \fBnormalizer\&.py\fP"
.br
.ti -1c
.RI "file \fBphoton_statistics\&.py\fP"
.br
.ti -1c
.RI "file \fBstatmethods\&.py\fP"
.br
.ti -1c
.RI "file \fBtest\&.py\fP"
.br
.ti -1c
.RI "file \fButilities\&.py\fP"
.br
.in -1c
