.TH "code Directory Reference" 3 "Thu Oct 14 2021" "Version 1.0" "DIY Auto-Correlator and Photon Statistics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBhardware\fP"
.br
.ti -1c
.RI "directory \fBpc_app\fP"
.br
.ti -1c
.RI "directory \fBsoftware\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBtypes\&.hpp\fP"
.br
.in -1c
