.TH "code/python Directory Reference" 3 "Fri Sep 17 2021" "Version 1.0" "DIY Auto-Correlator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/python Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBconfig\&.py\fP"
.br
.ti -1c
.RI "file \fBmultitau\&.py\fP"
.br
.ti -1c
.RI "file \fBpost_upload_actions\&.py\fP"
.br
.ti -1c
.RI "file \fBpre_build_actions\&.py\fP"
.br
.ti -1c
.RI "file \fButilities\&.py\fP"
.br
.in -1c
