.TH "Accumulator< Series_size >" 3 "Fri Sep 17 2021" "Version 1.0" "DIY Auto-Correlator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Accumulator< Series_size > \- Adapter object responsible for accumulating the points and coarsening the time-series as per the relavent linear-correlator time-resolution\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <accumulator\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBpipe\fP (\fBLin_ACorr_RT_Teensy\fP< Series_size > &channel, \fBcounter_t\fP datum) __attribute__((flatten))"
.br
.RI "Accumulates data points until the BufferPoints criteria is satisfied, after which the points are pushed to the channel\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned int \fBBufferPoints\fP = 0"
.br
.RI "Number of points accumulated and binned together\&. "
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "unsigned int \fBReceivedPointsCounter\fP = 0"
.br
.RI "Maximum number of points accepted by the accumulator\&. For debugging\&. "
.ti -1c
.RI "\fBcounter_t\fP \fBAccumulate\fP = 0\&.0"
.br
.RI "Stores the value of the accumulate\&. "
.ti -1c
.RI "unsigned int \fBLocalCounter\fP = 0"
.br
.RI "Maintains a cunter of the items to accumuate\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<index_t Series_size>
.br
class Accumulator< Series_size >"
Adapter object responsible for accumulating the points and coarsening the time-series as per the relavent linear-correlator time-resolution\&. 
.SH "Member Function Documentation"
.PP 
.SS "template<index_t Series_size> void \fBAccumulator\fP< Series_size >::pipe (\fBLin_ACorr_RT_Teensy\fP< Series_size > & channel, \fBcounter_t\fP datum)\fC [inline]\fP"

.PP
Accumulates data points until the BufferPoints criteria is satisfied, after which the points are pushed to the channel\&. 
.SH "Member Data Documentation"
.PP 
.SS "template<index_t Series_size> \fBcounter_t\fP \fBAccumulator\fP< Series_size >::Accumulate = 0\&.0\fC [private]\fP"

.PP
Stores the value of the accumulate\&. 
.SS "template<index_t Series_size> unsigned int \fBAccumulator\fP< Series_size >::BufferPoints = 0"

.PP
Number of points accumulated and binned together\&. 
.SS "template<index_t Series_size> unsigned int \fBAccumulator\fP< Series_size >::LocalCounter = 0\fC [private]\fP"

.PP
Maintains a cunter of the items to accumuate\&. 
.SS "template<index_t Series_size> unsigned int \fBAccumulator\fP< Series_size >::ReceivedPointsCounter = 0\fC [private]\fP"

.PP
Maximum number of points accepted by the accumulator\&. For debugging\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for DIY Auto-Correlator from the source code\&.
