.TH "Accumulator" 3 "Thu Oct 14 2021" "Version 1.0" "DIY Auto-Correlator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Accumulator \- Adapter object responsible for accumulating the points and coarsening the time-series as per the relavent linear-correlator time-resolution\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <accumulator\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBdo_accumulate\fP (unsigned int buffer_cnt)"
.br
.RI "Sets the number of points to buffer(accumulate) before pushing to Correlator object\&. "
.ti -1c
.RI "template<typename LinCorrType > void \fBpipe\fP (LinCorrType &channel, const \fBcounter_t\fP datum)"
.br
.RI "Accumulates data points until the BufferPoints criteria is satisfied, after which the points are pushed to the channel\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned int \fBBuffer_count\fP = 0"
.br
.RI "Number of points accumulated and binned together\&. "
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBcounter_t\fP \fBAccumulate\fP = 0"
.br
.RI "Stores the value of the accumulate\&. "
.ti -1c
.RI "unsigned int \fBUpdate_count\fP = 0"
.br
.RI "Maintains a counter of the items to accumuate\&. "
.in -1c
.SH "Detailed Description"
.PP 
Adapter object responsible for accumulating the points and coarsening the time-series as per the relavent linear-correlator time-resolution\&. 
.SH "Member Function Documentation"
.PP 
.SS "void Accumulator::do_accumulate (unsigned int buffer_cnt)\fC [inline]\fP"

.PP
Sets the number of points to buffer(accumulate) before pushing to Correlator object\&. 
.SS "template<typename LinCorrType > void Accumulator::pipe (LinCorrType & channel, const \fBcounter_t\fP datum)\fC [inline]\fP"

.PP
Accumulates data points until the BufferPoints criteria is satisfied, after which the points are pushed to the channel\&. 
.SH "Member Data Documentation"
.PP 
.SS "\fBcounter_t\fP Accumulator::Accumulate = 0\fC [private]\fP"

.PP
Stores the value of the accumulate\&. 
.SS "unsigned int Accumulator::Buffer_count = 0"

.PP
Number of points accumulated and binned together\&. 
.SS "unsigned int Accumulator::Update_count = 0\fC [private]\fP"

.PP
Maintains a counter of the items to accumuate\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for DIY Auto-Correlator from the source code\&.
