.TH "code/pc_app/config.py" 3 "Thu Oct 14 2021" "Version 1.0" "DIY Auto-Correlator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/pc_app/config.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBconfig\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBconfig\&.config_validation\fP (config)"
.br
.ti -1c
.RI "def \fBconfig\&.generate_config_file\fP ()"
.br
.ti -1c
.RI "def \fBconfig\&.fill_missing_in_config_file\fP (config_file)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "dictionary \fBconfig\&.default_config\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DIY Auto-Correlator from the source code\&.
