.TH "config" 3 "Thu Oct 14 2021" "Version 1.0" "DIY Auto-Correlator and Photon Statistics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
config
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBconfig_validation\fP (config)"
.br
.ti -1c
.RI "def \fBgenerate_config_file\fP ()"
.br
.ti -1c
.RI "def \fBfill_missing_in_config_file\fP (config_file)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "dictionary \fBdefault_config\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def config\&.config_validation ( config)"

.SS "def config\&.fill_missing_in_config_file ( config_file)"

.PP
.nf
Checks for missing fields in the configuration file and adds default values, if missing fields are found.
.fi
.PP
 
.SS "def config\&.generate_config_file ()"

.PP
.nf
Generates the json configuration file in the current working directory 
.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "dictionary config\&.default_config"

.SH "Author"
.PP 
Generated automatically by Doxygen for DIY Auto-Correlator and Photon Statistics from the source code\&.
