.TH "device_mode.DataStore" 3 "Fri Nov 12 2021" "Version 1.0" "DIY Auto-Correlator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
device_mode.DataStore
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, parent_path='\&.', session_name=None, save_to_file=True, force=False, test_dirs=False)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBname_\fP"
.br
.ti -1c
.RI "\fBsession_path\fP"
.br
.ti -1c
.RI "\fBdatasets\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBclass_lock\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Data Store is an object that manages creation of a session directory, 
and maintains a dictionary of references of objects in its scope.

.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def device_mode\&.DataStore\&.__init__ ( self,  parent_path = \fC'\&.'\fP,  session_name = \fCNone\fP,  save_to_file = \fCTrue\fP,  force = \fCFalse\fP,  test_dirs = \fCFalse\fP)"

.SH "Member Data Documentation"
.PP 
.SS "device_mode\&.DataStore\&.class_lock\fC [static]\fP"

.PP
.nf
Data Store is an object that manages creation of a session directory, 
and maintains a dictionary of references of objects in its scope.

.fi
.PP
 
.SS "device_mode\&.DataStore\&.datasets"

.SS "device_mode\&.DataStore\&.name_"

.SS "device_mode\&.DataStore\&.session_path"


.SH "Author"
.PP 
Generated automatically by Doxygen for DIY Auto-Correlator from the source code\&.
