.TH "device_mode.FeatureLine" 3 "Fri Nov 12 2021" "Version 1.0" "DIY Auto-Correlator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
device_mode.FeatureLine
.SH SYNOPSIS
.br
.PP
.PP
Inherits ABC\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBgenerate_data_files\fP (self)"
.br
.ti -1c
.RI "def \fBgenerate_data_fields\fP (self)"
.br
.ti -1c
.RI "def \fBget_parsar\fP (self)"
.br
.ti -1c
.RI "def \fBget_gui\fP (self)"
.br
.ti -1c
.RI "def \fBget_struct_size\fP (self)"
.br
.ti -1c
.RI "def \fBgenerate_struct_repr\fP (self)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Abstract class that defines the implementation for 
describing a feature line for PC end software. 

.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "def device_mode\&.FeatureLine\&.generate_data_fields ( self)"

.SS "def device_mode\&.FeatureLine\&.generate_data_files ( self)"

.SS "def device_mode\&.FeatureLine\&.generate_struct_repr ( self)"

.SS "def device_mode\&.FeatureLine\&.get_gui ( self)"

.SS "def device_mode\&.FeatureLine\&.get_parsar ( self)"

.SS "def device_mode\&.FeatureLine\&.get_struct_size ( self)"


.SH "Author"
.PP 
Generated automatically by Doxygen for DIY Auto-Correlator from the source code\&.
