.TH "Discarder_Teensy< Series_size, Front, End >" 3 "Mon Aug 30 2021" "Version 1.0" "DIY Auto-Correlator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Discarder_Teensy< Series_size, Front, End > \- Teensy specific Front back discarder implementation\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <discarder\&.hpp>\fP
.PP
Inherits \fBFrontBack_Discarder_Base< Series_size, Front, End >\fP\&.
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBoutput\fP (const \fBLin_ACorr_RT_Base\fP &channel) const override \fB__attribute__\fP((always\-inline))"
.br
.RI "Outputs the channel while discarding the selected channels, by using the implementation specific output method\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.SS "template<unsigned int Series_size, unsigned int Front, unsigned int End>
.br
class Discarder_Teensy< Series_size, Front, End >"
Teensy specific Front back discarder implementation\&. 
.SH "Member Function Documentation"
.PP 
.SS "template<unsigned int Series_size, unsigned int Front, unsigned int End> void \fBDiscarder_Teensy\fP< Series_size, Front, End >::output (const \fBLin_ACorr_RT_Base\fP & channel) const\fC [inline]\fP, \fC [override]\fP, \fC [private]\fP, \fC [virtual]\fP"

.PP
Outputs the channel while discarding the selected channels, by using the implementation specific output method\&. 
.PP
Implements \fBFrontBack_Discarder_Base< Series_size, Front, End >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DIY Auto-Correlator from the source code\&.
