.TH "code/software/discarder.hpp" 3 "Thu Oct 14 2021" "Version 1.0" "DIY Auto-Correlator and Photon Statistics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/software/discarder.hpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&./\&.\&./types\&.hpp'\fP
.br
\fC#include 'Lin_ACorr_RT_Teensy\&.hpp'\fP
.br
\fC#include <Arduino\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDiscarderTeensy< Series_size, Front, End >\fP"
.br
.RI "Teensy specific Front back discarder implementation\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DIY Auto-Correlator and Photon Statistics from the source code\&.
