.TH "Discarder_Teensy< Series_size, Front, End >" 3 "Fri Sep 17 2021" "Version 1.0" "DIY Auto-Correlator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Discarder_Teensy< Series_size, Front, End > \- Teensy specific Front back discarder implementation\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <discarder\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBoutput\fP (const \fBLin_ACorr_RT_Teensy\fP< Series_size > &channel) const __attribute__((always_inline))"
.br
.ti -1c
.RI "unsigned virtual int \fBdiscard_count\fP () const"
.br
.RI "Returns the number of elements discarded by the discarder object\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<unsigned int Series_size, unsigned int Front, unsigned int End>
.br
class Discarder_Teensy< Series_size, Front, End >"
Teensy specific Front back discarder implementation\&. 
.SH "Member Function Documentation"
.PP 
.SS "template<unsigned int Series_size, unsigned int Front, unsigned int End> unsigned virtual int \fBDiscarder_Teensy\fP< Series_size, Front, End >::discard_count () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Returns the number of elements discarded by the discarder object\&. 
.SS "template<unsigned int Series_size, unsigned int Front, unsigned int End> void \fBDiscarder_Teensy\fP< Series_size, Front, End >::output (const \fBLin_ACorr_RT_Teensy\fP< Series_size > & channel) const\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for DIY Auto-Correlator from the source code\&.
