.TH "/mnt/m/code/Correlator/Software/discarder.hpp" 3 "Mon Aug 30 2021" "Version 1.0" "DIY Auto-Correlator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/mnt/m/code/Correlator/Software/discarder.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'types\&.hpp'\fP
.br
\fC#include 'Lin_ACorr_RT_Base\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFrontBack_Discarder_Base< Series_size, Front, End >\fP"
.br
.RI "Base class for Front and Back discarder objects\&. "
.ti -1c
.RI "class \fBDiscarder_Teensy< Series_size, Front, End >\fP"
.br
.RI "Teensy specific Front back discarder implementation\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DIY Auto-Correlator from the source code\&.
