.TH "code/hardware/errors.hpp" 3 "Thu Oct 14 2021" "Version 1.0" "DIY Auto-Correlator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/hardware/errors.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'pins\&.hpp'\fP
.br
\fC#include '\&./\&.\&./types\&.hpp'\fP
.br
\fC#include 'ledpanel\&.hpp'\fP
.br
\fC#include <Arduino\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBErrors\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTEENSY_MAX_ALLOCATION\fP   125000"
.br
.RI "This file contain the Common Error Codes for Software-Hardware Interface\&. It defines the \fCError_t\fP and namespace \fC\fBErrors\fP\fP that are used to handle the errors and interact with the LED dashboard\&. "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBError_t\fP { \fBError_t::Success\fP = 0, \fBError_t::Counter_Overflow\fP, \fBError_t::Counter_Underflow\fP, \fBError_t::Precision\fP, \fBError_t::Input_Validation\fP, \fBError_t::Generic_Error\fP }
.RI "Enumarates the error codes thrown by the different modules\&. ""
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define TEENSY_MAX_ALLOCATION   125000"

.PP
This file contain the Common Error Codes for Software-Hardware Interface\&. It defines the \fCError_t\fP and namespace \fC\fBErrors\fP\fP that are used to handle the errors and interact with the LED dashboard\&. 
.PP
\fBAuthor:\fP
.RS 4
Yatharth Bhasin (github → yatharthb97) Maximum Allocations of 32-bit integers allowed on the microcontroller Teensy\&. 
.RE
.PP

.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBError_t\fP\fC [strong]\fP"

.PP
Enumarates the error codes thrown by the different modules\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fISuccess \fP\fP
No error\&. 
.TP
\fB\fICounter_Overflow \fP\fP
Passed Value caused a counter overflow\&. 
.TP
\fB\fICounter_Underflow \fP\fP
Passed Value caused a counter underflow\&. 
.TP
\fB\fIPrecision \fP\fP
Error generated when difference due to finite resolution is greater than acceptable\&. 
.TP
\fB\fIInput_Validation \fP\fP
Input validation failed\&. 
.TP
\fB\fIGeneric_Error \fP\fP
Only here for development and debugging\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for DIY Auto-Correlator from the source code\&.
