.TH "/mnt/m/code/Correlator/errors.hpp" 3 "Mon Aug 30 2021" "Version 1.0" "DIY Auto-Correlator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/mnt/m/code/Correlator/errors.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'pins\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBErrors\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBError_t\fP { \fBError_t::Success\fP = 0, \fBError_t::Counter_Overflow\fP, \fBError_t::Counter_Underflow\fP, \fBError_t::Precision\fP, \fBError_t::Input_Validation\fP }
.RI "Enumarates the error codes thrown by the different modules\&. ""
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBErrors::Validate\fP (\fBError_t\fP error)"
.br
.RI "Receives an error state and sets up the corresponding LED indicator\&. [[Incomplete]]\&. "
.ti -1c
.RI "void \fBErrors::Precison_Threshold\fP (double error_val, double error_limit)"
.br
.RI "Receives error value and error threshold and returns an appropriate error state\&. "
.ti -1c
.RI "template<unsigned int Lin_channels, index_t Series_size, unsigned int Bin_Ratio> \fBError_t\fP \fBErrors::Auto_MultiTau_Input_Validator\fP ()"
.br
.ti -1c
.RI "void \fB_assert_\fP (bool expression, char *\fB__attribute__\fP((unused)) message='') \fB__attribute__\fP((noreturn"
.br
.RI "Custom runtime assert function that sets all the dashboard LEDs to high\&. "
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBError_t\fP\fC [strong]\fP"

.PP
Enumarates the error codes thrown by the different modules\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fISuccess \fP\fP
.TP
\fB\fICounter_Overflow \fP\fP
No error\&. 
.TP
\fB\fICounter_Underflow \fP\fP
.TP
\fB\fIPrecision \fP\fP
.TP
\fB\fIInput_Validation \fP\fP
The error due to finite resolution is greater than acceptable\&. Input validation failed 
.SH "Function Documentation"
.PP 
.SS "void _assert_ (bool expression, char *\fB__attribute__\fP((unused)) message = \fC''\fP)"

.PP
Custom runtime assert function that sets all the dashboard LEDs to high\&. Custom assertion function\&. 
.PP
\fBParameters:\fP
.RS 4
\fIexpression\fP which must evaluate to false for the assertion to call abort\&. 
.br
\fImessage\fP which is ignored in the function, but helps with code redability 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for DIY Auto-Correlator from the source code\&.
