.TH "code/software/fakechannel.hpp" 3 "Fri Nov 12 2021" "Version 1.0" "DIY Auto-Correlator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/software/fakechannel.hpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&./\&.\&./types\&.hpp'\fP
.br
\fC#include 'simpler_circular_buffer\&.hpp'\fP
.br
\fC#include <Arduino\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFakeChannel< Series_Size, hasMonitorChannel >\fP"
.br
.RI "This is an \fIduck typed\fP implementaion of a \fILinear Correlator\fP that returns linearly increasing values for correlation\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DIY Auto-Correlator from the source code\&.
