.TH "src/featureline2.hpp" 3 "Thu Oct 14 2021" "Version 1.0" "DIY Auto-Correlator and Photon Statistics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/featureline2.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <Arduino\&.h>\fP
.br
\fC#include <imxrt\&.h>\fP
.br
\fC#include 'global\&.hpp'\fP
.br
\fC#include '\&./\&.\&./code/hardware/qtmr1\&.hpp'\fP
.br
\fC#include '\&./\&.\&./code/hardware/ledpanel\&.hpp'\fP
.br
\fC#include '\&./\&.\&./code/software/multi_tau\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsetup_interarrival\fP ()"
.br
.ti -1c
.RI "void \fBloop_interarrival\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void loop_interarrival ()"

.SS "void setup_interarrival ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for DIY Auto-Correlator and Photon Statistics from the source code\&.
