.TH "FrontBack_Discarder_Base< Series_size, Front, End >" 3 "Mon Aug 30 2021" "Version 1.0" "DIY Auto-Correlator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FrontBack_Discarder_Base< Series_size, Front, End > \- Base class for Front and Back discarder objects\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <discarder\&.hpp>\fP
.PP
Inherited by \fBDiscarder_Teensy< Series_size, Front, End >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void const \fBoutput\fP (const \fBLin_ACorr_RT_Base\fP &channel) const =0"
.br
.RI "Outputs the channel while discarding the selected channels, by using the implementation specific output method\&. "
.ti -1c
.RI "virtual void \fBdiscards\fP () const"
.br
.RI "Returns the number of elements discarded by the discarder object\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<unsigned int Series_size, unsigned int Front, unsigned int End>
.br
class FrontBack_Discarder_Base< Series_size, Front, End >"
Base class for Front and Back discarder objects\&. 
.SH "Member Function Documentation"
.PP 
.SS "template<unsigned int Series_size, unsigned int Front, unsigned int End> virtual void \fBFrontBack_Discarder_Base\fP< Series_size, Front, End >::discards () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Returns the number of elements discarded by the discarder object\&. 
.SS "template<unsigned int Series_size, unsigned int Front, unsigned int End> virtual void const \fBFrontBack_Discarder_Base\fP< Series_size, Front, End >::output (const \fBLin_ACorr_RT_Base\fP & channel) const\fC [inline]\fP, \fC [pure virtual]\fP"

.PP
Outputs the channel while discarding the selected channels, by using the implementation specific output method\&. 
.PP
Implemented in \fBDiscarder_Teensy< Series_size, Front, End >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DIY Auto-Correlator from the source code\&.
