.TH "src/global.cpp" 3 "Thu Oct 14 2021" "Version 1.0" "DIY Auto-Correlator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/global.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'global\&.hpp'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "\fBMultiTauACorrRTTeensy\fP< LIN_CORRS, SERIES_SIZE, BIN_RATIO > \fBmultitau\fP"
.br
.ti -1c
.RI "\fBPITController\fP< PIT_CHANNEL_IN_USE > \fBPI_t\fP"
.br
.RI "PI_t Resource\&. "
.ti -1c
.RI "\fBTMR1Controller\fP \fBTTL_c\fP"
.br
.RI "TTL_c Resource\&. "
.ti -1c
.RI "volatile \fBcounter_t\fP \fBCounter_val\fP = 0"
.br
.RI "Stores the value read from the counter\&. "
.ti -1c
.RI "volatile bool \fBUpdate_flag\fP = false"
.br
.RI "Indicates if a new value has arrived from the counting module\&. "
.ti -1c
.RI "volatile unsigned int \fBUpdate_count\fP = 0"
.br
.RI "Stores the number of updates made on the correlator channels since the last serialout\&. "
.ti -1c
.RI "uint32_t \fBSerialOut_After\fP = 100"
.br
.ti -1c
.RI "const double \fBGate_time_us\fP = GATE_TIME_US"
.br
.RI "Serial output is done after these many updates (default → overriden in the setup function)\&. "
.ti -1c
.RI "const double \fBAllowed_period_error_us\fP = ALLOWED_GATE_TIME_ERROR_US"
.br
.RI "The gate time of TTL_C in microseconds (us) "
.ti -1c
.RI "const int32_t \fBsync_code\fP = SYNC_CODE"
.br
.RI "Gate time precision error due to finite precision of timers\&. "
.ti -1c
.RI "float \fBarray\fP [CHANNEL_SIZE] = {0}"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const double Allowed_period_error_us = ALLOWED_GATE_TIME_ERROR_US"

.PP
The gate time of TTL_C in microseconds (us) 
.SS "float array[CHANNEL_SIZE] = {0}"

.SS "volatile \fBcounter_t\fP Counter_val = 0"

.PP
Stores the value read from the counter\&. 
.SS "const double Gate_time_us = GATE_TIME_US"

.PP
Serial output is done after these many updates (default → overriden in the setup function)\&. 
.SS "\fBMultiTauACorrRTTeensy\fP<LIN_CORRS, SERIES_SIZE, BIN_RATIO> multitau"

.SS "\fBPITController\fP<PIT_CHANNEL_IN_USE> PI_t"

.PP
PI_t Resource\&. 
.SS "uint32_t SerialOut_After = 100"

.SS "const int32_t sync_code = SYNC_CODE"

.PP
Gate time precision error due to finite precision of timers\&. 
.SS "\fBTMR1Controller\fP TTL_c"

.PP
TTL_c Resource\&. 
.SS "volatile unsigned int Update_count = 0"

.PP
Stores the number of updates made on the correlator channels since the last serialout\&. 
.SS "volatile bool Update_flag = false"

.PP
Indicates if a new value has arrived from the counting module\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for DIY Auto-Correlator from the source code\&.
