.TH "code/software/histogram.hpp" 3 "Thu Oct 14 2021" "Version 1.0" "DIY Auto-Correlator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/software/histogram.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <type_traits>\fP
.br
\fC#include '\&./\&.\&./types\&.hpp'\fP
.br
\fC#include <Arduino\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPCHistogram< BinType, Bins >\fP"
.br
.RI "Photon Counting Histogram module for Real time calculation on \fITeensy 4\&.1 microcontrollers\fP\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DIY Auto-Correlator from the source code\&.
