.TH "Interrupt" 3 "Mon Aug 30 2021" "Version 1.0" "DIY Auto-Correlator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Interrupt
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBPITController< ChID >::interrupt\fP () \fB__attribute__\fP((always_inline))"
.br
.RI "Enable Interruptsthat are triggered after one gate time completion\&. "
.ti -1c
.RI "void \fBPITController< ChID >::no_interrupt\fP () \fB__attribute__\fP((always_inline))"
.br
.RI "Disable Interrupts that are triggered after one gate time completion\&. "
.ti -1c
.RI "static void \fBPITController< ChID >::set_interrupt\fP (void(*isr_fn)(), unsigned int priority) \fB__attribute__\fP((always_inline))"
.br
.RI "Sets a common ISR and its priority for all PIT Channels\&. "
.ti -1c
.RI "void \fBPITController< ChID >::clear_interrupt_flag\fP () \fB__attribute__\fP((always_inline))"
.br
.RI "Clears the interrupt flag and hence prepares the timer for the next gate interval\&. The clearing has to be done manually\&. If the flag is not cleared, the interrupt will be called again and again\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SH "Function Documentation"
.PP 
.SS "template<unsigned int ChID> void \fBPITController\fP< ChID >::clear_interrupt_flag ()\fC [inline]\fP"

.PP
Clears the interrupt flag and hence prepares the timer for the next gate interval\&. The clearing has to be done manually\&. If the flag is not cleared, the interrupt will be called again and again\&. 
.SS "template<unsigned int ChID> void \fBPITController\fP< ChID >::interrupt ()\fC [inline]\fP"

.PP
Enable Interruptsthat are triggered after one gate time completion\&. 
.SS "template<unsigned int ChID> void \fBPITController\fP< ChID >::no_interrupt ()\fC [inline]\fP"

.PP
Disable Interrupts that are triggered after one gate time completion\&. 
.SS "template<unsigned int ChID> static void \fBPITController\fP< ChID >::set_interrupt (void(*)() isr_fn, unsigned int priority)\fC [inline]\fP, \fC [static]\fP"

.PP
Sets a common ISR and its priority for all PIT Channels\&. 
.PP
\fBNote:\fP
.RS 4
All PIT channels share a single ISR on Teensy 4\&.x micro-controllers\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for DIY Auto-Correlator from the source code\&.
