.TH "src/ledpanel.cpp" 3 "Thu Oct 14 2021" "Version 1.0" "DIY Auto-Correlator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ledpanel.cpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&./\&.\&./code/hardware/ledpanel\&.hpp'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "\fBLEDSet\fP< 5 > \fBLEDPanel\fP ({LED_BUILTIN, \fBLED_RED\fP, \fBLED_GREEN\fP, \fBLED_WHITE\fP, \fBLED_BLUE\fP})"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBLEDSet\fP<5> LEDPanel({LED_BUILTIN, \fBLED_RED\fP, \fBLED_GREEN\fP, \fBLED_WHITE\fP, \fBLED_BLUE\fP})"

.SH "Author"
.PP 
Generated automatically by Doxygen for DIY Auto-Correlator from the source code\&.
