.TH "code/hardware/ledpanel.hpp" 3 "Thu Oct 14 2021" "Version 1.0" "DIY Auto-Correlator and Photon Statistics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/hardware/ledpanel.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'ledset\&.hpp'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for DIY Auto-Correlator and Photon Statistics from the source code\&.
