.TH "code/hardware/ledset.hpp" 3 "Thu Oct 14 2021" "Version 1.0" "DIY Auto-Correlator and Photon Statistics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/hardware/ledset.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <Arduino\&.h>\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include 'pins\&.hpp'\fP
.br
\fC#include <array>\fP
.br
\fC#include <initializer_list>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLEDSet< SET_SIZE >\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DIY Auto-Correlator and Photon Statistics from the source code\&.
