.TH "LEDSet" 3 "Mon Aug 30 2021" "Version 1.0" "DIY Auto-Correlator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LEDSet
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ledset\&.hpp>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static unsigned int \fBsize\fP () \fB__attribute__\fP((always_inline))"
.br
.RI "Returns the size of the led sets\&. "
.ti -1c
.RI "static void \fBinit\fP ()"
.br
.RI "Sets up the pin mode of all LEDs\&. "
.ti -1c
.RI "static void \fBstate_reload\fP ()"
.br
.RI "Sets the LEDs digitally to max brighnes, based on their switch state\&. "
.ti -1c
.RI "static void \fBtoggle_all\fP ()"
.br
.RI "Toggles the state of all the LEDs\&. "
.ti -1c
.RI "static \fBtoggle_all_routine\fP (int delay_ms)"
.br
.RI "Toggles all the LEDs twice, with some delay\&.  Animation\&. "
.ti -1c
.RI "static void \fBdim\fP (unsigned int analog_val)"
.br
.RI "Dims the ON-LEDs with the provided analog voltage\&. Only affects LEDs that are ON\&. "
.ti -1c
.RI "static void \fBdim_routine\fP (unsigned int end_analog_val)"
.br
.RI "Slowly dims the ON-LEDs with a routine that lasts 1s\&.  Animation\&. "
.ti -1c
.RI "static void \fBmin_brighness\fP ()"
.br
.RI "Sets maximum brightness for all ON-LEDs\&. "
.ti -1c
.RI "static void \fBmin_brightness\fP ()"
.br
.ti -1c
.RI "static \fBset_all\fP () \fB__attribute__\fP((always_inline))"
.br
.RI "Turn on all available LEDs\&. "
.ti -1c
.RI "static \fBunset_all\fP () \fB__attribute__\fP((always_inline))"
.br
.ti -1c
.RI "static void \fBset\fP (int led_pin) \fB__attribute__\fP((always_inline))"
.br
.RI "Turn-ON a particular LED Pin\&. "
.ti -1c
.RI "static void \fBunset\fP (int led_pin) \fB__attribute__\fP((always_inline))"
.br
.RI "Turn-OFF a particular LED Pin\&. "
.ti -1c
.RI "static void \fBset\fP (int led_pin1, int led_pin2) \fB__attribute__\fP((always_inline))"
.br
.RI "Turn-ON two LED Pins simultaneously\&. "
.ti -1c
.RI "static void \fBunset\fP (int led_pin1, int led_pin2) \fB__attribute__\fP((always_inline))"
.br
.RI "Turn-OFF two LED Pins simultaneously\&. "
.ti -1c
.RI "static void \fBset\fP (int led_pin1, int led_pin2, int led_pin3) \fB__attribute__\fP((always_inline))"
.br
.RI "Turn-ON three LED Pins simultaneously\&. "
.ti -1c
.RI "static void \fBunset\fP (int led_pin1, int led_pin2, int led_pin3) \fB__attribute__\fP((always_inline))"
.br
.RI "Turn-FF three LED Pins simultaneously\&. "
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr int \fBLEDs\fP [6] = {BUILTLIN, \fBLED_RED\fP, \fBLED_BLUE\fP, \fBLED_YELLOW\fP, \fBLED_WHITE\fP, \fBLED_GREEN\fP}"
.br
.ti -1c
.RI "static constexpr bool \fBLEDStatus\fP [6] = {false}"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "int \fBfetch_index\fP (int pin) \fB__attribute__\fP((always_inline))"
.br
.RI "Retrive data structure index based on the pin number\&. "
.in -1c
.SH "Detailed Description"
.PP 
an interface for accessing the LEDs on the dashboard and the BUILTIN LED\&. Theobject serves primarily as a bookeeping object, and hence, enables state conservation and switching\&. 
.SH "Member Function Documentation"
.PP 
.SS "static void LEDSet::dim (unsigned int analog_val)\fC [inline]\fP, \fC [static]\fP"

.PP
Dims the ON-LEDs with the provided analog voltage\&. Only affects LEDs that are ON\&. 
.SS "static void LEDSet::dim_routine (unsigned int end_analog_val)\fC [inline]\fP, \fC [static]\fP"

.PP
Slowly dims the ON-LEDs with a routine that lasts 1s\&.  Animation\&. 
.SS "int LEDSet::fetch_index (int pin)\fC [inline]\fP, \fC [private]\fP"

.PP
Retrive data structure index based on the pin number\&. 
.SS "static void LEDSet::init ()\fC [inline]\fP, \fC [static]\fP"

.PP
Sets up the pin mode of all LEDs\&. 
.SS "static void LEDSet::min_brighness ()\fC [inline]\fP, \fC [static]\fP"

.PP
Sets maximum brightness for all ON-LEDs\&. 
.SS "static void LEDSet::min_brightness ()\fC [inline]\fP, \fC [static]\fP"
Sets the minimum brighness for all ON-LEDs\&. 
.SS "static void LEDSet::set (int led_pin)\fC [inline]\fP, \fC [static]\fP"

.PP
Turn-ON a particular LED Pin\&. 
.SS "static void LEDSet::set (int led_pin1, int led_pin2)\fC [inline]\fP, \fC [static]\fP"

.PP
Turn-ON two LED Pins simultaneously\&. 
.SS "static void LEDSet::set (int led_pin1, int led_pin2, int led_pin3)\fC [inline]\fP, \fC [static]\fP"

.PP
Turn-ON three LED Pins simultaneously\&. 
.SS "static LEDSet::set_all ()\fC [inline]\fP, \fC [static]\fP"

.PP
Turn on all available LEDs\&. 
.SS "static unsigned int LEDSet::size ()\fC [inline]\fP, \fC [static]\fP"

.PP
Returns the size of the led sets\&. 
.SS "static void LEDSet::state_reload ()\fC [inline]\fP, \fC [static]\fP"

.PP
Sets the LEDs digitally to max brighnes, based on their switch state\&. 
.SS "static void LEDSet::toggle_all ()\fC [inline]\fP, \fC [static]\fP"

.PP
Toggles the state of all the LEDs\&. 
.SS "static LEDSet::toggle_all_routine (int delay_ms)\fC [inline]\fP, \fC [static]\fP"

.PP
Toggles all the LEDs twice, with some delay\&.  Animation\&. 
.SS "static void LEDSet::unset (int led_pin)\fC [inline]\fP, \fC [static]\fP"

.PP
Turn-OFF a particular LED Pin\&. 
.SS "static void LEDSet::unset (int led_pin1, int led_pin2)\fC [inline]\fP, \fC [static]\fP"

.PP
Turn-OFF two LED Pins simultaneously\&. 
.SS "static void LEDSet::unset (int led_pin1, int led_pin2, int led_pin3)\fC [inline]\fP, \fC [static]\fP"

.PP
Turn-FF three LED Pins simultaneously\&. 
.SS "static LEDSet::unset_all ()\fC [inline]\fP, \fC [static]\fP"
Turn off all available LEDs\&. 
.SH "Member Data Documentation"
.PP 
.SS "constexpr int LEDSet::LEDs[6] = {BUILTLIN, \fBLED_RED\fP, \fBLED_BLUE\fP, \fBLED_YELLOW\fP, \fBLED_WHITE\fP, \fBLED_GREEN\fP}\fC [static]\fP"

.SS "constexpr bool LEDSet::LEDStatus[6] = {false}\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for DIY Auto-Correlator from the source code\&.
