.TH "LEDSet" 3 "Wed Sep 1 2021" "Version 1.0" "DIY Auto-Correlator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LEDSet
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ledset\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLEDSet\fP ()"
.br
.RI "Constructor for \fBLEDSet\fP class\&. "
.ti -1c
.RI "constexpr unsigned int \fBsize\fP () __attribute__((always_inline))"
.br
.RI "Returns the size of the led sets\&. "
.ti -1c
.RI "void \fBinit\fP ()"
.br
.RI "Sets up the pin mode of all LEDs\&. "
.ti -1c
.RI "void \fBstate_reload\fP ()"
.br
.RI "Sets the LEDs digitally to max brighnes, based on their switch state\&. "
.ti -1c
.RI "void \fBtoggle_all\fP ()"
.br
.RI "Toggles the state of all the LEDs\&. "
.ti -1c
.RI "void \fBtoggle_all_routine\fP (int delay_ms)"
.br
.ti -1c
.RI "void \fBdim\fP (unsigned int analog_val)"
.br
.RI "Dims the ON-LEDs with the provided analog voltage\&. Only affects LEDs that are ON\&. "
.ti -1c
.RI "void \fBdim_routine\fP (unsigned int end_analog_val)"
.br
.ti -1c
.RI "void \fBmin_brighness\fP ()"
.br
.RI "Sets maximum brightness for all ON-LEDs\&. "
.ti -1c
.RI "void \fBmin_brightness\fP ()"
.br
.ti -1c
.RI "void \fBset_all\fP () __attribute__((always_inline))"
.br
.RI "Turn on all available LEDs\&. "
.ti -1c
.RI "void \fBunset_all\fP () __attribute__((always_inline))"
.br
.ti -1c
.RI "void \fBset\fP (int led_pin) __attribute__((always_inline))"
.br
.RI "Turn-ON a particular LED Pin\&. "
.ti -1c
.RI "void \fBunset\fP (int led_pin) __attribute__((always_inline))"
.br
.RI "Turn-OFF a particular LED Pin\&. "
.ti -1c
.RI "void \fBset\fP (int led_pin1, int led_pin2) __attribute__((always_inline))"
.br
.RI "Turn-ON two LED Pins simultaneously\&. "
.ti -1c
.RI "void \fBunset\fP (int led_pin1, int led_pin2) __attribute__((always_inline))"
.br
.RI "Turn-OFF two LED Pins simultaneously\&. "
.ti -1c
.RI "void \fBset\fP (int led_pin1, int led_pin2, int led_pin3) __attribute__((always_inline))"
.br
.RI "Turn-ON three LED Pins simultaneously\&. "
.ti -1c
.RI "void \fBunset\fP (int led_pin1, int led_pin2, int led_pin3) __attribute__((always_inline))"
.br
.RI "Turn-FF three LED Pins simultaneously\&. "
.ti -1c
.RI "void \fBerror\fP (int pin) __attribute__((always_inline))"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const int \fBLEDs\fP [6] = {LED_BUILTIN, \fBLED_RED\fP, \fBLED_BLUE\fP, \fBLED_YELLOW\fP, \fBLED_WHITE\fP, \fBLED_GREEN\fP}"
.br
.ti -1c
.RI "bool \fBLEDStatus\fP [6]"
.br
.ti -1c
.RI "bool \fBError_State\fP"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "int \fBfetch_index\fP (int pin) __attribute__((always_inline))"
.br
.RI "Retrive data structure index based on the pin number\&. Returns -1 if the pin was not found\&. "
.in -1c
.SH "Detailed Description"
.PP 
an interface for accessing the LEDs on the dashboard and the BUILTIN LED\&. Theobject serves primarily as a bookeeping object, and hence, enables state conservation and switching\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "LEDSet::LEDSet ()\fC [inline]\fP"

.PP
Constructor for \fBLEDSet\fP class\&. 
.SH "Member Function Documentation"
.PP 
.SS "void LEDSet::dim (unsigned int analog_val)\fC [inline]\fP"

.PP
Dims the ON-LEDs with the provided analog voltage\&. Only affects LEDs that are ON\&. 
.SS "void LEDSet::dim_routine (unsigned int end_analog_val)\fC [inline]\fP"

.SS "void LEDSet::error (int pin)\fC [inline]\fP"

.SS "int LEDSet::fetch_index (int pin)\fC [inline]\fP, \fC [private]\fP"

.PP
Retrive data structure index based on the pin number\&. Returns -1 if the pin was not found\&. 
.PP
\fBReturns:\fP
.RS 4
Local array index of pin in the LEDs array (bookeeping object)\&. -1 if the search fails\&. 
.RE
.PP

.SS "void LEDSet::init ()\fC [inline]\fP"

.PP
Sets up the pin mode of all LEDs\&. 
.SS "void LEDSet::min_brighness ()\fC [inline]\fP"

.PP
Sets maximum brightness for all ON-LEDs\&. 
.SS "void LEDSet::min_brightness ()\fC [inline]\fP"
Sets the minimum brighness for all ON-LEDs\&. 
.SS "void LEDSet::set (int led_pin)\fC [inline]\fP"

.PP
Turn-ON a particular LED Pin\&. 
.SS "void LEDSet::set (int led_pin1, int led_pin2)\fC [inline]\fP"

.PP
Turn-ON two LED Pins simultaneously\&. 
.SS "void LEDSet::set (int led_pin1, int led_pin2, int led_pin3)\fC [inline]\fP"

.PP
Turn-ON three LED Pins simultaneously\&. 
.SS "void LEDSet::set_all ()\fC [inline]\fP"

.PP
Turn on all available LEDs\&. 
.SS "constexpr unsigned int LEDSet::size ()\fC [inline]\fP"

.PP
Returns the size of the led sets\&. 
.SS "void LEDSet::state_reload ()\fC [inline]\fP"

.PP
Sets the LEDs digitally to max brighnes, based on their switch state\&. 
.SS "void LEDSet::toggle_all ()\fC [inline]\fP"

.PP
Toggles the state of all the LEDs\&. 
.SS "void LEDSet::toggle_all_routine (int delay_ms)\fC [inline]\fP"

.SS "void LEDSet::unset (int led_pin)\fC [inline]\fP"

.PP
Turn-OFF a particular LED Pin\&. 
.SS "void LEDSet::unset (int led_pin1, int led_pin2)\fC [inline]\fP"

.PP
Turn-OFF two LED Pins simultaneously\&. 
.SS "void LEDSet::unset (int led_pin1, int led_pin2, int led_pin3)\fC [inline]\fP"

.PP
Turn-FF three LED Pins simultaneously\&. 
.SS "void LEDSet::unset_all ()\fC [inline]\fP"
Turn off all available LEDs\&. 
.SH "Member Data Documentation"
.PP 
.SS "bool LEDSet::Error_State"

.SS "const int LEDSet::LEDs[6] = {LED_BUILTIN, \fBLED_RED\fP, \fBLED_BLUE\fP, \fBLED_YELLOW\fP, \fBLED_WHITE\fP, \fBLED_GREEN\fP}"

.SS "bool LEDSet::LEDStatus[6]"


.SH "Author"
.PP 
Generated automatically by Doxygen for DIY Auto-Correlator from the source code\&.
