.TH "code/hardware/lifetime_timer.hpp" 3 "Thu Oct 14 2021" "Version 1.0" "DIY Auto-Correlator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/hardware/lifetime_timer.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <imxrt\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPIT_LifetimeTimer\fP"
.br
.RI "Interface for using the 'Life Time TImer' functionality of the Periodic Interrut Timer on Teensy 4\&.x microcontrollers\&. The module uses Channel 0 and 1 of the 4 PIT channels\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DIY Auto-Correlator from the source code\&.
