.TH "lib/software/Lin_CrossCorr_RT_Base.hpp" 3 "Wed Sep 1 2021" "Version 1.0" "DIY Auto-Correlator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/software/Lin_CrossCorr_RT_Base.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'types\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLin_CrossCorr_RT_Base\fP"
.br
.RI "This class is a blank interface for all objects that are — \fB{Linear\fP Real-Time Software Auto-Correlators}\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DIY Auto-Correlator from the source code\&.
