.TH "Lin_ACorr_RT_Base" 3 "Fri Sep 3 2021" "Version 1.0" "DIY Auto-Correlator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Lin_ACorr_RT_Base \- This class is a blank interface for all objects that are — \fB{Linear\fP Real-Time Software Auto-Correlators}\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Lin_ACorr_RT_Base\&.hpp>\fP
.PP
Inherited by \fBLin_ACorr_RT_Teensy< Series_size >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBpush_datum\fP (\fBcounter_t\fP datum)=0"
.br
.RI "Accepts a single \fCdatum\fP from the counter — which is the lowest order of data aggregate, appends to Series_array and updates relevant channels\&. "
.ti -1c
.RI "virtual void \fBpush_data\fP (const \fBcounter_t\fP *container, const index_t size)=0"
.br
.RI "Repeatedy calls \fCLin_ACorr_RT_Base::push_datam()\fP on all the elements of the countainer\&. "
.ti -1c
.RI "virtual double \fBnorm\fP (index_t lag)=0"
.br
.RI "Takes in the lag value and returns the normalization (divider) for the passed lag value\&. "
.ti -1c
.RI "virtual void \fBch_out\fP () const =0"
.br
.RI "Outputs all the channels using specific implementation based methods\&. "
.ti -1c
.RI "virtual void \fBch_out_norm\fP () const =0"
.br
.RI "Outputs all the channels with \fB\fP <normalisation> using specific implementation based methods\&. "
.ti -1c
.RI "virtual \fBcounter_t\fP * \fBget_ch_array\fP () const =0"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class is a blank interface for all objects that are — \fB{Linear\fP Real-Time Software Auto-Correlators}\&. 
.SH "Member Function Documentation"
.PP 
.SS "virtual double Lin_ACorr_RT_Base::norm (index_t lag)\fC [inline]\fP, \fC [pure virtual]\fP"

.PP
Takes in the lag value and returns the normalization (divider) for the passed lag value\&. 
.SS "virtual void Lin_ACorr_RT_Base::push_data (const \fBcounter_t\fP * container, const index_t size)\fC [inline]\fP, \fC [pure virtual]\fP"

.PP
Repeatedy calls \fCLin_ACorr_RT_Base::push_datam()\fP on all the elements of the countainer\&. 
.SS "virtual void Lin_ACorr_RT_Base::push_datum (\fBcounter_t\fP datum)\fC [inline]\fP, \fC [pure virtual]\fP"

.PP
Accepts a single \fCdatum\fP from the counter — which is the lowest order of data aggregate, appends to Series_array and updates relevant channels\&. 
.PP
Implemented in \fBLin_ACorr_RT_Teensy< Series_size >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DIY Auto-Correlator from the source code\&.
