.TH "lib/software/Lin_ACorr_RT_Teensy.hpp" 3 "Wed Sep 1 2021" "Version 1.0" "DIY Auto-Correlator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/software/Lin_ACorr_RT_Teensy.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'types\&.hpp'\fP
.br
\fC#include 'Lin_ACorr_RT_Base\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLin_ACorr_RT_Teensy< Series_size >\fP"
.br
.RI "This is an implementation of \fBLin_ACorr_RT_Base\fP for Teensy with \fB\fP(No normalisation or baseline subtraction\&.) "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DIY Auto-Correlator from the source code\&.
