.TH "code/software/Lin_ACorr_RT_Teensy.hpp" 3 "Fri Nov 12 2021" "Version 1.0" "DIY Auto-Correlator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/software/Lin_ACorr_RT_Teensy.hpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&./\&.\&./types\&.hpp'\fP
.br
\fC#include 'simpler_circular_buffer\&.hpp'\fP
.br
\fC#include <Arduino\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLinACorrRTTeensy< Series_Size, hasMonitorChannel >\fP"
.br
.RI "This is an implementation of Lin_ACorr_RT_Base for Teensy with \fB\fP(No normalisation or baseline subtraction\&.) "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DIY Auto-Correlator from the source code\&.
