.TH "livegraph" 3 "Thu Oct 14 2021" "Version 1.0" "DIY Auto-Correlator and Photon Statistics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
livegraph
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBLiveGraph\fP (xRange=None, yRange=None, kwargs)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def livegraph\&.LiveGraph ( xRange = \fCNone\fP,  yRange = \fCNone\fP,  kwargs)"

.SH "Author"
.PP 
Generated automatically by Doxygen for DIY Auto-Correlator and Photon Statistics from the source code\&.
