.TH "src/main.cpp" 3 "Thu Oct 14 2021" "Version 1.0" "DIY Auto-Correlator and Photon Statistics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'featureline1\&.hpp'\fP
.br
\fC#include 'featureline2\&.hpp'\fP
.br
\fC#include 'featureline3\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.RI "Main Function\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"

.PP
Main Function\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for DIY Auto-Correlator and Photon Statistics from the source code\&.
