.TH "src/main.cpp" 3 "Fri Sep 3 2021" "Version 1.0" "DIY Auto-Correlator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <Arduino\&.h>\fP
.br
\fC#include '\&./\&.\&./code/software/multi_tau\&.hpp'\fP
.br
\fC#include '\&./\&.\&./code/hardware/pit\&.hpp'\fP
.br
\fC#include '\&./\&.\&./code/hardware/pins\&.hpp'\fP
.br
\fC#include '\&./\&.\&./code/hardware/qtmr1\&.hpp'\fP
.br
\fC#include '\&./\&.\&./code/hardware/utilities\&.hpp'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBOTHER_PIN\fP   4"
.br
.ti -1c
.RI "#define \fBDELAY\fP   100"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsetup\fP ()"
.br
.ti -1c
.RI "void \fBloop\fP ()"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DELAY   100"

.SS "#define OTHER_PIN   4"

.SH "Function Documentation"
.PP 
.SS "void loop ()"

.SS "void setup ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for DIY Auto-Correlator from the source code\&.
