.TH "multitau" 3 "Thu Oct 14 2021" "Version 1.0" "DIY Auto-Correlator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
multitau
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBchannel_size\fP (lin_corrs, series_size, bin_ratio)"
.br
.ti -1c
.RI "def \fBx_tics\fP (lin_corrs, series_size, bin_ratio)"
.br
.ti -1c
.RI "def \fBpoints_scale_template\fP (lin_corrs, series_size, bin_ratio)"
.br
.ti -1c
.RI "def \fBbin_ratio_scale\fP (lin_corrs, series_size, bin_ratio)"
.br
.ti -1c
.RI "def \fBtau_max\fP (lin_corrs, series_size, bin_ratio)"
.br
.ti -1c
.RI "def \fBtime_axis_s\fP (tau_axis, gate_time_ms)"
.br
.ti -1c
.RI "def \fBpoints_norm\fP (lin_corrs, series_size, bin_ratio, LC0_points)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def multitau\&.bin_ratio_scale ( lin_corrs,  series_size,  bin_ratio)"

.PP
.nf
Returns an array of size `channel_size` that scales as per the `multitau scheme` bin ratio.

.fi
.PP
 
.SS "def multitau\&.channel_size ( lin_corrs,  series_size,  bin_ratio)"

.PP
.nf
Returns the expected channel size based on the multi-tau parameters.

.fi
.PP
 
.SS "def multitau\&.points_norm ( lin_corrs,  series_size,  bin_ratio,  LC0_points)"

.PP
.nf
Generates and returns a list of normalisation values based on the data points fed to 
the 0th Linear Correlator.

.fi
.PP
 
.SS "def multitau\&.points_scale_template ( lin_corrs,  series_size,  bin_ratio)"

.PP
.nf
Generates and returns a list of normalisation values, which when multiplied by the points
fed to the 0th linear Correlator - gives a list of points normalization values for all
the tau values.

.fi
.PP
 
.SS "def multitau\&.tau_max ( lin_corrs,  series_size,  bin_ratio)"

.PP
.nf
Returns the maximum tau-value for the given multi-tau configuration.

.fi
.PP
 
.SS "def multitau\&.time_axis_s ( tau_axis,  gate_time_ms)"

.PP
.nf
Returns the converted time axis in seconds based 
on gate_time(minimum resolution) in microseconds.

.fi
.PP
 
.SS "def multitau\&.x_tics ( lin_corrs,  series_size,  bin_ratio)"

.PP
.nf
Generates and returns a list of x-ticks that can be used for plotting, using the 
multi-tau parameters.

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for DIY Auto-Correlator from the source code\&.
