.TH "code/pc_app/multitau.py" 3 "Thu Oct 14 2021" "Version 1.0" "DIY Auto-Correlator and Photon Statistics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/pc_app/multitau.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBmultitau\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBmultitau\&.channel_size\fP (lin_corrs, series_size, bin_ratio)"
.br
.ti -1c
.RI "def \fBmultitau\&.x_tics\fP (lin_corrs, series_size, bin_ratio)"
.br
.ti -1c
.RI "def \fBmultitau\&.points_scale_template\fP (lin_corrs, series_size, bin_ratio)"
.br
.ti -1c
.RI "def \fBmultitau\&.bin_ratio_scale\fP (lin_corrs, series_size, bin_ratio)"
.br
.ti -1c
.RI "def \fBmultitau\&.tau_max\fP (lin_corrs, series_size, bin_ratio)"
.br
.ti -1c
.RI "def \fBmultitau\&.time_axis_s\fP (tau_axis, gate_time_ms)"
.br
.ti -1c
.RI "def \fBmultitau\&.points_norm\fP (lin_corrs, series_size, bin_ratio, LC0_points)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DIY Auto-Correlator and Photon Statistics from the source code\&.
