.TH "code/software/multi_tau.hpp" 3 "Fri Nov 12 2021" "Version 1.0" "DIY Auto-Correlator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/software/multi_tau.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <cmath>\fP
.br
\fC#include '\&./\&.\&./types\&.hpp'\fP
.br
\fC#include 'Lin_ACorr_RT_Teensy\&.hpp'\fP
.br
\fC#include 'accumulator\&.hpp'\fP
.br
\fC#include 'discarder\&.hpp'\fP
.br
\fC#include 'monitor_channel\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMultiTauACorrRTTeensy< Lin_channels, Series_size, Bin_Ratio >\fP"
.br
.RI "MultiTau Auto-Correlator object that is composed of multiple linear - autocorrelators\&. Specialised for teensy\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DIY Auto-Correlator from the source code\&.
