.TH "new_app" 3 "Fri Nov 12 2021" "Version 1.0" "DIY Auto-Correlator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
new_app
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBParamStruct\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBupdate_fn\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBstop_code_asserted\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def new_app\&.update_fn ()"

.SH "Variable Documentation"
.PP 
.SS "new_app\&.stop_code_asserted"

.SH "Author"
.PP 
Generated automatically by Doxygen for DIY Auto-Correlator from the source code\&.
