.TH "code/pc_app/normalizer.py" 3 "Thu Oct 14 2021" "Version 1.0" "DIY Auto-Correlator and Photon Statistics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/pc_app/normalizer.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBnormalizer\&.Normalizer\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBnormalizer\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DIY Auto-Correlator and Photon Statistics from the source code\&.
