.TH "code/hardware/perf_counter.hpp" 3 "Fri Nov 12 2021" "Version 1.0" "DIY Auto-Correlator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/hardware/perf_counter.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <imxrt\&.h>\fP
.br
\fC#include <Arduino\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPerfCounter\fP"
.br
.RI "Performance Counter class for teensy 4\&.1 microcontrollers\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DIY Auto-Correlator from the source code\&.
