.TH "/mnt/m/code/Correlator/pins.hpp" 3 "Mon Aug 30 2021" "Version 1.0" "DIY Auto-Correlator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/mnt/m/code/Correlator/pins.hpp
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "const int \fBLED_RED\fP = 41"
.br
.ti -1c
.RI "const int \fBLED_BLUE\fP = 42"
.br
.ti -1c
.RI "const int \fBLED_YELLOW\fP = 22"
.br
.ti -1c
.RI "const int \fBLED_WHITE\fP = 23"
.br
.ti -1c
.RI "const int \fBLED_GREEN\fP = 24"
.br
.ti -1c
.RI "const int \fBSAFE_INPUT_DUMP_PIN\fP = 0"
.br
.ti -1c
.RI "const int \fBSAFE_OUTPUT_DUMP_PIN\fP = 0"
.br
.ti -1c
.RI "const int \fBTTL_C_PULSE_INPUT_PIN\fP = 10"
.br
.ti -1c
.RI "const int \fBER_PRECISION_PIN\fP = \fBLED_BLUE\fP"
.br
.ti -1c
.RI "const int \fBER_OVERFLOW_PIN\fP = \fBLED_RED\fP"
.br
.ti -1c
.RI "const int \fBER_INPUT_VALIDATION\fP = \fBLED_YELLOW\fP"
.br
.ti -1c
.RI "const int \fBSETUP_LED\fP = \fBLED_WHITE\fP"
.br
.ti -1c
.RI "const int \fBLOOP_LED\fP = \fBLED_GREEN\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const int ER_INPUT_VALIDATION = \fBLED_YELLOW\fP"

.SS "const int ER_OVERFLOW_PIN = \fBLED_RED\fP"

.SS "const int ER_PRECISION_PIN = \fBLED_BLUE\fP"

.SS "const int LED_BLUE = 42"

.SS "const int LED_GREEN = 24"

.SS "const int LED_RED = 41"

.SS "const int LED_WHITE = 23"

.SS "const int LED_YELLOW = 22"

.SS "const int LOOP_LED = \fBLED_GREEN\fP"

.SS "const int SAFE_INPUT_DUMP_PIN = 0"

.SS "const int SAFE_OUTPUT_DUMP_PIN = 0"

.SS "const int SETUP_LED = \fBLED_WHITE\fP"

.SS "const int TTL_C_PULSE_INPUT_PIN = 10"

.SH "Author"
.PP 
Generated automatically by Doxygen for DIY Auto-Correlator from the source code\&.
