.TH "code/hardware/pit.hpp" 3 "Fri Sep 17 2021" "Version 1.0" "DIY Auto-Correlator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/hardware/pit.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'errors\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPITController< ChID >\fP"
.br
.RI "Interface for PIT timers on Teensy 4\&.x microcontrollers\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DIY Auto-Correlator from the source code\&.
