.TH "PIT_Glb" 3 "Mon Aug 30 2021" "Version 1.0" "DIY Auto-Correlator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PIT_Glb
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "static void \fBPITController< ChID >::enable_PITs\fP () \fB__attribute__\fP((always_inline))"
.br
.RI "Enable all PIT channels\&. "
.ti -1c
.RI "static void \fBPITController< ChID >::disable_PITs\fP () \fB__attribute__\fP((always_inline))"
.br
.RI "Disable all PIT Channels\&. "
.ti -1c
.RI "static void \fBPITController< ChID >::pause_resume_PITs\fP () \fB__attribute__\fP((always_inline))"
.br
.RI "Pause/Resume - \fBToggle\fP all PIT Channels\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SH "Function Documentation"
.PP 
.SS "template<unsigned int ChID> static void \fBPITController\fP< ChID >::disable_PITs ()\fC [inline]\fP, \fC [static]\fP"

.PP
Disable all PIT Channels\&. 
.SS "template<unsigned int ChID> static void \fBPITController\fP< ChID >::enable_PITs ()\fC [inline]\fP, \fC [static]\fP"

.PP
Enable all PIT channels\&. 
.SS "template<unsigned int ChID> static void \fBPITController\fP< ChID >::pause_resume_PITs ()\fC [inline]\fP, \fC [static]\fP"

.PP
Pause/Resume - \fBToggle\fP all PIT Channels\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for DIY Auto-Correlator from the source code\&.
