.TH "pre_build_actions" 3 "Fri Sep 17 2021" "Version 1.0" "DIY Auto-Correlator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pre_build_actions
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBafter_upload_action\fP (args, kwargs)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBf\fP = open('\&./config\&.json', 'r')"
.br
.ti -1c
.RI "\fBconfig\fP = json\&.load(\fBf\fP)"
.br
.ti -1c
.RI "\fBCPPDEFINES\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def pre_build_actions\&.after_upload_action ( args,  kwargs)"

.SH "Variable Documentation"
.PP 
.SS "pre_build_actions\&.config = json\&.load(\fBf\fP)"

.SS "pre_build_actions\&.CPPDEFINES"

.SS "pre_build_actions\&.f = open('\&./config\&.json', 'r')"

.SH "Author"
.PP 
Generated automatically by Doxygen for DIY Auto-Correlator from the source code\&.
