.TH "code/hardware/qtmr1.hpp" 3 "Thu Oct 14 2021" "Version 1.0" "DIY Auto-Correlator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/hardware/qtmr1.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'errors\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTMR1Controller\fP"
.br
.RI "Templated interface for Quad Timer 1 channels for Gate Counting\&. The module uses the macro \fC_TMR1_CONTROLLER_CH_\fP to identify the main channel and then assigns the next channel's (\fITMR1_CONTROLLER_CH\fP + 1) external pin to the \fITMR1_CONTROLLER_CH\fP as the 'Capture Pin' or the 'Secondary Count Source'\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_TMR1_CONTROLLER_CH_\fP   0"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define _TMR1_CONTROLLER_CH_   0"

.SH "Author"
.PP 
Generated automatically by Doxygen for DIY Auto-Correlator from the source code\&.
