.TH "statmethods.StatMethods" 3 "Fri Nov 12 2021" "Version 1.0" "DIY Auto-Correlator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
statmethods.StatMethods
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBvar_estimator\fP (first_moment, second_moment, size)"
.br
.ti -1c
.RI "def \fBnorm_lag0_estimator\fP (mean, variance)"
.br
.ti -1c
.RI "def \fBacf_amplitude\fP (norm_acf)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "def statmethods\&.StatMethods\&.acf_amplitude ( norm_acf)"

.SS "def statmethods\&.StatMethods\&.norm_lag0_estimator ( mean,  variance)"

.SS "def statmethods\&.StatMethods\&.var_estimator ( first_moment,  second_moment,  size)"


.SH "Author"
.PP 
Generated automatically by Doxygen for DIY Auto-Correlator from the source code\&.
