.TH "test" 3 "Fri Nov 12 2021" "Version 1.0" "DIY Auto-Correlator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBx\fP = np\&.load('acf_x\&.npy')"
.br
.ti -1c
.RI "\fBy\fP = np\&.load('acf_y\&.npy')"
.br
.ti -1c
.RI "\fBlg\fP = LiveGraph(yRange=0\&.04)"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "test\&.lg = LiveGraph(yRange=0\&.04)"

.SS "test\&.x = np\&.load('acf_x\&.npy')"

.SS "test\&.y = np\&.load('acf_y\&.npy')"

.SH "Author"
.PP 
Generated automatically by Doxygen for DIY Auto-Correlator from the source code\&.
