.TH "/mnt/m/code/Correlator/test.hpp" 3 "Mon Aug 30 2021" "Version 1.0" "DIY Auto-Correlator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/mnt/m/code/Correlator/test.hpp
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBget_capture_signal_pin\fP ()"
.br
.RI "Returns the pin number on which the capture signal must be connected\&. "
.ti -1c
.RI "void \fBinit_extern_pins\fP (int channel) \fB__attribute__\fP((always_inline))"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "IOMUXC_SW_MUX_CTL_PAD_GPIO_AD_B0_04 & \fBIOMUXC_SW_MUX_CTL_PAD_GPIO_AD_B0_04\fP = MUX_MODE(6)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int get_capture_signal_pin ()"

.PP
Returns the pin number on which the capture signal must be connected\&. 
.PP
\fBAttention:\fP
.RS 4
This function does not configure the pin and assign it to the QTMR module, for that TMR1Controller::init_pin() must be called\&. 
.RE
.PP

.SS "void init_extern_pins (int channel)"

.SH "Variable Documentation"
.PP 
.SS "IOMUXC_SW_MUX_CTL_PAD_GPIO_AD_B0_04& IOMUXC_SW_MUX_CTL_PAD_GPIO_AD_B0_04 = MUX_MODE(6)"

.SH "Author"
.PP 
Generated automatically by Doxygen for DIY Auto-Correlator from the source code\&.
