.TH "/mnt/m/code/Correlator/Software/test.cpp" 3 "Mon Aug 30 2021" "Version 1.0" "DIY Auto-Correlator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/mnt/m/code/Correlator/Software/test.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include 'multi_tau\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBsetup\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBMultiTau_ACorr_RT_Teensy\fP< 9, 27, 3 > \fBcorrelator\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int setup ()"

.SH "Variable Documentation"
.PP 
.SS "\fBMultiTau_ACorr_RT_Teensy\fP<9, 27, 3> correlator"

.SH "Author"
.PP 
Generated automatically by Doxygen for DIY Auto-Correlator from the source code\&.
