.TH "todo" 3 "Thu Oct 14 2021" "Version 1.0" "DIY Auto-Correlator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todoTodo List 
 \- 
.IP "\fBMember \fBErrors::Auto_MultiTau_Input_Validator\fP ()\fP" 1c
Change name to indicate \fIAuto\fP Correlator link\&.  
.IP "\fBClass \fBPIT_LifetimeTimer\fP \fP" 1c
Resolve Singleton template - constexpr static issue\&. 
.PP

