.TH "todo" 3 "Wed Sep 1 2021" "Version 1.0" "DIY Auto-Correlator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todoTodo List 
 \- 
.IP "\fBMember \fBErrors::Validate\fP (Error_t error)\fP" 1c
Complete this function for all error codes\&.  
.IP "\fBClass \fBPIT_LifetimeTimer\fP \fP" 1c
Resolve Singleton template - constexpr static issue\&. 
.PP

