.TH "code/types.hpp" 3 "Thu Oct 14 2021" "Version 1.0" "DIY Auto-Correlator and Photon Statistics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/types.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <cstdint>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPIT_CHANNEL_IN_USE\fP   2"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBcounter_t\fP = uint32_t"
.br
.RI "Data type received from the pulse counter\&. It is the fundamental type used for representing series data\&. "
.ti -1c
.RI "using \fBindex_t\fP = uint32_t"
.br
.RI "It is used as the array indices and thus determine the maximum size of the Channel_array and the Series_array\&. "
.ti -1c
.RI "using \fBchannel_t\fP = float"
.br
.RI "It is the data type used to store channel information\&. "
.ti -1c
.RI "using \fBchar8cast_t\fP = char"
.br
.RI "This is the type used for casting values into 8-bit units before putting them to Serial buffer\&. "
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define PIT_CHANNEL_IN_USE   2"

.SH "Typedef Documentation"
.PP 
.SS "using \fBchannel_t\fP =  float"

.PP
It is the data type used to store channel information\&. 
.SS "using \fBchar8cast_t\fP =  char"

.PP
This is the type used for casting values into 8-bit units before putting them to Serial buffer\&. 
.SS "using \fBcounter_t\fP =  uint32_t"

.PP
Data type received from the pulse counter\&. It is the fundamental type used for representing series data\&. 
.SS "using \fBindex_t\fP =  uint32_t"

.PP
It is used as the array indices and thus determine the maximum size of the Channel_array and the Series_array\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for DIY Auto-Correlator and Photon Statistics from the source code\&.
