.TH "code/types.hpp" 3 "Thu Oct 14 2021" "Version 1.0" "DIY Auto-Correlator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/types.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <cstdint>\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBcounter_t\fP = uint32_t"
.br
.RI "Data type received from the pulse counter\&. It is the fundamental type used for representing series data\&. "
.ti -1c
.RI "using \fBindex_t\fP = uint_fast8_t"
.br
.RI "It is used as the array indices and thus determine the maximum size of the Channel_array and the Series_array\&. "
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "using \fBcounter_t\fP =  uint32_t"

.PP
Data type received from the pulse counter\&. It is the fundamental type used for representing series data\&. 
.SS "using \fBindex_t\fP =  uint_fast8_t"

.PP
It is used as the array indices and thus determine the maximum size of the Channel_array and the Series_array\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for DIY Auto-Correlator from the source code\&.
