.TH "lib/types.hpp" 3 "Wed Sep 1 2021" "Version 1.0" "DIY Auto-Correlator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/types.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <cstdint>\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBcounter_t\fP = uint_fast32_t"
.br
.RI "Data type received from the pulse counter\&. It is the fundamental type used for representing series data\&. "
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "using \fBcounter_t\fP =  uint_fast32_t"

.PP
Data type received from the pulse counter\&. It is the fundamental type used for representing series data\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for DIY Auto-Correlator from the source code\&.
