.TH "code/python/utilities.py" 3 "Fri Sep 17 2021" "Version 1.0" "DIY Auto-Correlator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/python/utilities.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fButilities\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fButilities\&.PseudoConsole\fP ()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DIY Auto-Correlator from the source code\&.
