.TH "utilities" 3 "Thu Oct 14 2021" "Version 1.0" "DIY Auto-Correlator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
utilities
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBPseudoConsole\fP ()"
.br
.ti -1c
.RI "def \fBWelcomeText\fP (name)"
.br
.ti -1c
.RI "def \fBperiodic_callbacks\fP (period_ms, fn, args)"
.br
.ti -1c
.RI "def \fBStructRepresentation\fP (config)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def utilities\&.periodic_callbacks ( period_ms,  fn,  args)"

.SS "def utilities\&.PseudoConsole ()"

.SS "def utilities\&.StructRepresentation ( config)"

.SS "def utilities\&.WelcomeText ( name)"

.SH "Author"
.PP 
Generated automatically by Doxygen for DIY Auto-Correlator from the source code\&.
