.TH "src/utilities.cpp" 3 "Fri Sep 17 2021" "Version 1.0" "DIY Auto-Correlator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/utilities.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <cstdint>\fP
.br
\fC#include <cmath>\fP
.br
\fC#include <imxrt\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "uint32_t \fBserial_max_count\fP (double \fBGate_time_us\fP, double Serial_out_time_ms)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "uint32_t serial_max_count (double Gate_time_us, double Serial_out_time_ms)"

.SH "Author"
.PP 
Generated automatically by Doxygen for DIY Auto-Correlator from the source code\&.
