.TH "code/pc_app/utilities.py" 3 "Thu Oct 14 2021" "Version 1.0" "DIY Auto-Correlator and Photon Statistics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/pc_app/utilities.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fButilities\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fButilities\&.PseudoConsole\fP ()"
.br
.ti -1c
.RI "def \fButilities\&.WelcomeText\fP (name)"
.br
.ti -1c
.RI "def \fButilities\&.periodic_callbacks\fP (period_ms, fn, args)"
.br
.ti -1c
.RI "def \fButilities\&.StructRepresentation\fP (config)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DIY Auto-Correlator and Photon Statistics from the source code\&.
